### ISSUE TITLE
Web Video Problem

### ISSUE THREAD

**Issue by Git-Hoon** [saminsakur/PyQt5BrowserBuild#1]
Hello, I found that your browser can't watch web video on it. Is there any solution.

你好，我发现你的浏览器不能在其上观看网页视频，请问有什么解决办法吗。

**Comment by saminsakur** [comment]
Do you mean FULLSCREEN video? Video works fine here. Please try again.

**Comment by Git-Hoon** [comment]
No, I mean that I can not play videos on some streaming platform websites. They says 'Your browser version is too low' or 'Our platform does not support your browser'. I've got several projects and they all have this problem. I heard that Pyqt5's Chrome kernel version is too low......

**Comment by saminsakur** [comment]
Yes that's write. Sites like Whatsapp Web faces the same problem but there are nothing I can do for this. If the framework PyQt5 does not have the latest chromium version.

**Comment by Git-Hoon** [comment]
Waiting for update for PyQt5 if posible...
